// AUTOGENERATED by RG1 (skeleton)
// mock: 
// mode: ura
// file: input_ura_char.dart

import 'package:flutter/material.dart';

class InputScreenUra extends StatelessWidget {
  const InputScreenUra({super.key});

  @override
  Widget build(BuildContext context) {
    // 未接続：main.dart や routes は触らない（挙動差分ゼロ）
    return const Scaffold(
      body: SizedBox.shrink(),
    );
  }
}
