// AUTOGENERATED by RG1 (skeleton)
// mock: 
// mode: normal
// file: generate_normal_no_char.dart

import 'package:flutter/material.dart';

class GenerateScreenNoChar extends StatelessWidget {
  const GenerateScreenNoChar({super.key});

  @override
  Widget build(BuildContext context) {
    // 未接続：main.dart や routes は触らない（挙動差分ゼロ）
    return const Scaffold(
      body: SizedBox.shrink(),
    );
  }
}
