// AUTOGENERATED by RG1 (skeleton)
// mock: 
// mode: normal
// file: input_normal_nochar.dart

import 'package:flutter/material.dart';

class InputNormalScreen extends StatelessWidget {
  const InputNormalScreen({super.key});

  @override
  Widget build(BuildContext context) {
    // 未接続：main.dart や routes は触らない（挙動差分ゼロ）
    return const Scaffold(
      body: SizedBox.shrink(),
    );
  }
}
