#!/usr/bin/env python3
# RG1: 雛形コード自動生成スクリプト（未接続・安全）
# CSV: docs/design/mock_mapping_canonical.csv
# 出力: lib/screens/{normal,ura}/<suggested_dart_file>

import csv, os, sys, re

CSV_PATH = "docs/design/mock_mapping_canonical.csv"
BASE_DIR = "lib/screens"

# 司令室CSVの列名（想定）
COL_MOCK  = "mock_file"
COL_MODE  = "mode"                   # normal / ura
COL_FILE  = "suggested_dart_file"    # 例: generate_ura_no_char.dart
COL_CLASS = "suggested_class"        # 例: GenerateScreenUraNoChar

def ensure_dirs():
    os.makedirs(os.path.join(BASE_DIR, "normal"), exist_ok=True)
    os.makedirs(os.path.join(BASE_DIR, "ura"), exist_ok=True)

def read_csv_rows(path):
    # エンコーディングゆらぎに耐える
    for enc in ("utf-8", "utf-8-sig", "cp932", "shift_jis"):
        try:
            with open(path, newline="", encoding=enc) as f:
                return list(csv.DictReader(f))
        except UnicodeDecodeError:
            continue
    print(f"[ERROR] cannot decode CSV: {path}", file=sys.stderr)
    sys.exit(1)
    
def infer_mode(row):
    mode = (row.get("mode") or "").strip().lower()
    if mode in ("normal","ura"):
        return mode
    # 1) route から推測
    route = (row.get("suggested_route") or "").lower()
    if "/ura" in route:
        return "ura"
    if "/normal" in route:
        return "normal"
    # 2) ファイル名・クラス名から推測
    for key in ("suggested_dart_file","suggested_class","mock_file","screen"):
        val = (row.get(key) or "").lower()
        if "ura" in val:
            return "ura"
        if "normal" in val:
            return "normal"
    return ""  # 判定不能
    
def main():
    if not os.path.isfile(CSV_PATH):
        print(f"[ERROR] CSV not found: {CSV_PATH}", file=sys.stderr)
        sys.exit(1)

    ensure_dirs()
    rows = read_csv_rows(CSV_PATH)

    created = []
    for i, row in enumerate(rows, start=1):
        mock  = (row.get(COL_MOCK)  or "").strip()
        mode  = infer_mode(row)
        dfile = (row.get(COL_FILE)  or "").strip()
        cls   = (row.get(COL_CLASS) or "").strip()

        # 必須チェック
        if mode not in ("normal", "ura"):
            print(f"[SKIP] row {i}: invalid mode '{mode}'");  continue
        if not dfile or not cls:
            print(f"[SKIP] row {i}: missing file/class");      continue
        if not dfile.endswith(".dart"):
            dfile += ".dart"

        out_dir = os.path.join(BASE_DIR, mode)
        out_path = os.path.join(out_dir, dfile)

        # 既存ファイルは上書き禁止
        if os.path.exists(out_path):
            print(f"[EXIST] {out_path} -> skip")
            continue

        content = f"""// AUTOGENERATED by RG1 (skeleton)
// mock: {mock}
// mode: {mode}
// file: {dfile}

import 'package:flutter/material.dart';

class {cls} extends StatelessWidget {{
  const {cls}({{super.key}});

  @override
  Widget build(BuildContext context) {{
    // 未接続：main.dart や routes は触らない（挙動差分ゼロ）
    return const Scaffold(
      body: SizedBox.shrink(),
    );
  }}
}}
"""
        with open(out_path, "w", encoding="utf-8") as fp:
            fp.write(content)
        created.append(out_path)
        print(f"[CREATE] {out_path}")

    # 生成一覧を補助ファイルに
    list_path = "tools/rg1_created_files.txt"
    with open(list_path, "w", encoding="utf-8") as fp:
        fp.write("\n".join(created) + ("\n" if created else ""))
    print(f"\n[INFO] Created {len(created)} file(s). List -> {list_path}")

if __name__ == "__main__":
    main()
